# Generated by Django 4.0 on 2024-02-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='suppliers.Supplier'),
        ),
    ]
