# Generated by Django 4.0 on 2024-02-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('new', 'Новый'), ('in_process', 'В_процессе'), ('completed', 'Завершен')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
